version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - n 16.14.2
  pre_build:
    commands:
      - cd app
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - ls
artifacts:
  files:
    - '**/*'
  base-directory: 'app/build'
